### ISSUE TITLE
점주 회원가입창이 필요합니다.

### ISSUE THREAD

**Issue by 10wook** [KioSSGk/kiossgk#1]
점주에 대한 C(생성)를 만들어주세요
<img width="465" alt="스크린샷 2024-07-23 오전 10 32 55" src="https://github.com/user-attachments/assets/da9ac106-80fd-4788-9cb5-4a85cf95da9e">

**Comment by leedonguk0809** [comment]
가게 이미지 생성 입력창도 만들어주세요

**Comment by SugarRaccoon** [comment]
![image](https://github.com/user-attachments/assets/c2d8bad1-0fde-4355-8e8b-ba17e7841978)
이 화면으로 만들어주세요

**Comment by leedonguk0809** [comment]
@SugarRaccoon 사업장 이름이 빠져있습니다.
그리고 가게 이미지는 첨부파일 입니다. 추가해서 다시 올려주세요

**Comment by SugarRaccoon** [comment]
![image](https://github.com/user-attachments/assets/d8296ea9-e01e-416d-8cc9-69c6b68efbf6)
수정 완료했습니다
