### ISSUE TITLE
깃 클론으로 다운로드시 노드js 인스톨이 추가로 필요하다고 합니다. 

### ISSUE THREAD

**Issue by 10wook** [KioSSGk/kiossgk#3]
현재 이와 같은 문제가 발생중인데 같은 문제가 발생하는 분들은 댓글 달아주세요.

해결법을 알아내게 되었으면 알려주세요.

**Comment by system421** [comment]
npm install을 실행하면 해결됩니다.

**Comment by 10wook** [comment]
파일들이 깃 IGNORE되어 있어서 발생한 문제였는데, 말씀 주신대로 npm install 하면 해결 됩니다.

하여 다운로드 된 파일들도 어차피 깃에 영향을 주지 않으니 이대로 진행하면 될 듯 합니다.
